// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgfCALQbN8Nqu56jTRciJp5Tkj-Bokcc4',
    appId: '1:560517619542:android:b6ebef4327b3d6003bc0f7',
    messagingSenderId: '560517619542',
    projectId: 'food-delivery-38a42',
    storageBucket: 'food-delivery-38a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwZIWFzFuz1ZzX1qXpU7PO5L5bu0KOIzc',
    appId: '1:560517619542:ios:1fc221d77fa95ea43bc0f7',
    messagingSenderId: '560517619542',
    projectId: 'food-delivery-38a42',
    storageBucket: 'food-delivery-38a42.appspot.com',
    iosBundleId: 'com.example.ubereatsdriver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDzWOU8lhlXUnsjG-ylB370xW03UJ3Ao',
    appId: '1:560517619542:web:154a48f7740241043bc0f7',
    messagingSenderId: '560517619542',
    projectId: 'food-delivery-38a42',
    authDomain: 'food-delivery-38a42.firebaseapp.com',
    storageBucket: 'food-delivery-38a42.appspot.com',
    measurementId: 'G-CDQ477JSR2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwZIWFzFuz1ZzX1qXpU7PO5L5bu0KOIzc',
    appId: '1:560517619542:ios:1fc221d77fa95ea43bc0f7',
    messagingSenderId: '560517619542',
    projectId: 'food-delivery-38a42',
    storageBucket: 'food-delivery-38a42.appspot.com',
    iosBundleId: 'com.example.ubereatsdriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNDzWOU8lhlXUnsjG-ylB370xW03UJ3Ao',
    appId: '1:560517619542:web:5070bc37bbf2af363bc0f7',
    messagingSenderId: '560517619542',
    projectId: 'food-delivery-38a42',
    authDomain: 'food-delivery-38a42.firebaseapp.com',
    storageBucket: 'food-delivery-38a42.appspot.com',
    measurementId: 'G-78CKZLML5B',
  );

}